### ISSUE TITLE
Revision 000f of Model B is missing

### ISSUE THREAD

**Issue by goszpeti** [UedaTakeyuki/getrpimodel#2]
Hello,

in the line model_b = ["0002","0004","0005","0006","000d","000e","000e",] the last entry should be 000f model, which I incidentally have and returns None for my Raspberry Pi model.

**Comment by UedaTakeyuki** [comment]
Hi, goszpeti

You are right, I've missed revision 000f.
I'll fix it soon.

**Comment by UedaTakeyuki** [comment]
Hi, goszpeti

I've fixed it and released an updated version on pypi.
I'm sorry to bother you but would you please update this module and tell me the result? Thank you!

**Comment by goszpeti** [comment]
Hello, 

thank you for the quick reaction and fix, it works now perfectly and returns "B".
